unit bbshc;

interface

const hcHelp      = 3000;
      hcDosShell  = 3001;
      hcRemark    = 3002;
      hcMouseDlg  = 3003;
      hcColors    = 3004;
      hcAbout     = 3005;
      hcVideoMode = 3006;
      hcSaveDesk  = 3007;
      hcLoadDesk  = 3008;
      hcExternal  = 3009;

      hcHelpIndex  = 3020;
      hcHelpOnHelp = 3021;
      hcGlobalHelp = 3022;

      hcTile       = 3030;
      hcCascade    = 3031;
      hcResize     = 3032;
      hcZoom       = 3033;
      hcNext       = 3034;
      hcClose      = 3035;
      hcPrev       = 3036;




      hcSystemMenu = 3050;
      hcDeskMenu   = 3051;
      hcHelpMenu   = 3052;
      hcWindowsMenu = 3053;

      hcQuit       = 3099;

      hcInViewer  = 3100;

implementation

end.
